apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:V8EpsMI=,iv:a9nXat1Gubrnxk4fBftY0ftwIEWQ9xcjqRhDOZjIp40=,tag:vmTRmG/dno1BsjcyincYDA==,type:str]
    admin-password: ENC[AES256_GCM,data:fwd9V24b827L9mecqGmklWVTsSY=,iv:BLLUkpVVOEpFzZ5xAdDfApTJcjdKa2EJOeq0udddi4s=,tag:+Woc3oXcIYIzOeWGQgbGQQ==,type:str]
sops:
    age:
        - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDekVqSFVBR1JPSnJPYlVu
            YjhMN2ZYcDZZYUF4NncyRHdVazA2cm1LTlVVClVrcUF1Z0ZmWHF3Z2VXeTRGRTNn
            Rm84T0t2WjhHV3dRTkdGZlB4elROZGsKLS0tIDljTnJ0SFMxM3U1R3ladVh5ZHJZ
            L3lDZkJyaFZ1RVhaa2lRVEdEc2VxV3cKmYFRP9Hb8T8Vf0eQVAB+FND/Qmf/AM9r
            U4QIl+DhXqbCCnK25Ab/0Yt6JY0Lp4tgwnlBeoRElPzf2GT3KS8hdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcGRZOUlZQW9zUmxCeklY
            b0pZQlFsNXNoSjZ4WWNtVEpLVldZSlp1WGxnCnlYbE9HSElmTEsyMkp1NEFZb2dL
            d0tDcTZjRmlKSGJTenRQWVBOUCsrNVkKLS0tIHkrRkt5N2hvNVVKNGp4NjVXaHFN
            VW9DM3M3U0R0RDNLNmVPM08zUHJSVHcKjeeCGHV3J1Wl8NBuLKM4r+gXIMqyaCmY
            4ddBGMlKlrlm91NGym+BgKN5xsYpq+Wh2f5PxJHVn/j9Hc4vyFD+PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T00:48:33Z"
    mac: ENC[AES256_GCM,data:zkiPfwOE1xL5onGCYqBdFErK046V9ni9YYPXKW8ntv8pdwWqwps+xyUmkD8fC9JbP1gQbSLwzjvMfbPyLQxHtpLMvtIP8OwYVQl3RS+BNaiKa9MdheE+LgvFRqyfoUvcQFoCGPSwUI2paPa3EjHPkH2CnV93u9qjk1c41WYT+hc=,iv:y/evyiGT17kde5WKIGarpflwQdj/4scne0p5jq+dtlQ=,tag:IBQQr0W0i8gDCkxdR0B/xA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
