---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    grafana:
      admin:
        existingSecret: grafana-admin
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        enabled: true
        ingressclassName: traefik
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.dev.men.sh
        hosts:
          - grafana.dev.men.sh
