apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-pg
  namespace: zitadel
spec:
  instances: 1
  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
