apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  releaseName: zitadel
  chart:
    spec:
      chart: zitadel
      sourceRef:
        kind: HelmRepository
        name: zitadel
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    zitadel:
      masterkeySecretName: existing-zitadel-masterkey

      configmapConfig:
        ExternalDomain: welcher.men.sh
        ExternalSecure: true
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: zitadel-pg-rw.zitadel.svc.cluster.local
            Port: 5432
            Database: zitadel
            User:
              Username: zitadel
              SSL:
                Mode: verify-full
            Admin:
              Username: postgres
              SSL:
                Mode: verify-full
        FirstInstance:
          Org:
            Human:
              # In case UserLoginMustBeDomain is false (default) and you don't overwrite the username with an email,
              # it will be suffixed by the org domain (org-name + domain from config).
              # for example zitadel-admin in org ZITADEL on domain.tld -> zitadel-admin@zitadel.domain.tld
              UserName: zitadel-admin # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
              FirstName: ZITADEL # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME
              LastName: Admin # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME
              NickName: # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_NICKNAME
              DisplayName: # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_DISPLAYNAME
              Email:
                # uses the username if empty
                Address: info@naegele.dev
                Verified: true # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED
              Password: Password1! # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
              PasswordChangeRequired: true # ZITADEL_FIRSTINSTANCE_ORG_H
            Machine:
              Machine:
                Username: "iam-admin"
                Name: "Automatically Initialized IAM Admin"
              MachineKey:
                ExpirationDate: "2029-01-01T00:00:00Z"
                Type: 1
              # If this Pat object is present, a PAT will also be created.
              Pat:
                ExpirationDate: "2029-01-01T00:00:00Z"

            # Defines the internal machine user required by the ZITADEL Login UI.
            # This user communicates with the main ZITADEL API to handle login flows.
            # It is a specialized, internal-use-only account and is not intended for
            # general administrative use. A PAT is generated and stored in a
            # Kubernetes secret named 'login-client'.
            LoginClient:
              Machine:
                Username: "login-client"
                Name: "Automatically Initialized IAM Login Client"
              # The expiration date for the Login UI's Personal Access Token (PAT).
              Pat:
                ExpirationDate: "2029-01-01T00:00:00Z"
      dbSslCaCrtSecret: zitadel-pg-ca
      dbSslAdminCrtSecret: zitadel-pg-server

    ingress:
      enabled: true
      className: traefik

    login:
      enabled: true
      ingress:
        enabled: true
        className: traefik

    env:
      - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-pg-app
            key: password
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-pg-superuser
            key: password

    initJob:
      command: "zitadel"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
