apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  releaseName: zitadel
  chart:
    spec:
      chart: zitadel
      sourceRef:
        kind: HelmRepository
        name: zitadel
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    zitadel:
      masterkeySecretName: existing-zitadel-masterkey

      configmapConfig:
        ExternalDomain: welcher.men.sh
        ExternalSecure: true
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: zitadel-pg-rw.zitadel.svc.cluster.local
            Port: 5432
            Database: zitadel
            User:
              Username: zitadel
              SSL:
                Mode: verify-full
            Admin:
              Username: postgres
              SSL:
                Mode: verify-full
        FirstInstance:
          Org:
            Human:
              UserName: zitadel-admin # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
              FirstName: ZITADEL # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME
              LastName: Admin # ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME
              Email:
                Address: info@naegele.dev
                Verified: true
              Password: Password1!
              PasswordChangeRequired: true
            Machine:
              Machine:
                Username: "iam-admin"
                Name: "Automatically Initialized IAM Admin"
              MachineKey:
                ExpirationDate: "2029-01-01T00:00:00Z"
                Type: 1
              Pat:
                ExpirationDate: "2029-01-01T00:00:00Z"
            LoginClient:
              Machine:
                Username: "login-client"
                Name: "Automatically Initialized IAM Login Client"
              Pat:
                ExpirationDate: "2029-01-01T00:00:00Z"
      dbSslCaCrtSecret: zitadel-pg-ca
      dbSslAdminCrtSecret: zitadel-pg-server

    ingress:
      enabled: true
      className: traefik

    login:
      enabled: true
      ingress:
        enabled: true
        className: traefik

    env:
      - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-pg-app
            key: password
      - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zitadel-pg-superuser
            key: password

    initJob:
      command: "zitadel"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
