apiVersion: v1
kind: Secret
metadata:
    name: existing-zitadel-masterkey
    type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:M3uXC02Qx319ufaiFkbYmF99hq90B8h16l+wv0TYq+I=,iv:7LD3DbL/nuvoHozQFHAKgKI4X6KuiISclxQkqbksVKs=,tag:xHALICN9DA5hZI8VaPrWjg==,type:str]
sops:
    age:
        - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ2pGd0E0aTFlM3kzNHVn
            cmZTL1lmYWd2R3BxLzNZWk5HVml3cFRPeWk0CnNBbDJrcDcrM2l4VnVJWHd2WEtS
            d2FNZm1NREFadkZqVEhzZFJTbUh0VWsKLS0tIDY0VVd1Y0tCRXhMNEVITkR1RG1L
            cjJaL3ZQQTltMmZRNTd4Q1lwZXJZUmsKGJDQ+CueFa1jYgxsbUYZZd44bqCXE77m
            GuF0JFS56YEQdmcOm/Zs1GRPAAc7hO1kYA3opCSXP5g+xg9fS/qnhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYmxkek9SSTVjQksxZ3B3
            anp3MTl5QWZNeGo2SVBZUnpPSzhuU2dUdFNjCkQ2TFo0RkU3K3dRUEhSaXFlRkRX
            UjFlVElOQ25iaUhRa29qRjdsUGRoVUUKLS0tIEdHUlpwTSt3ZnBDMXlONUtwMCt2
            OXE1ckEvTHFPTUFLVjYvVHhPVmNPRlkKVXIOxEqktEKECR6OMExkrkj9Ac9IBZba
            DZyeKbW1aHjXNqzi/Oa9+Zc08vXcC25rejVGyE6+NB/uPivjhuzgmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T19:10:54Z"
    mac: ENC[AES256_GCM,data:ozcDHON1NtTql50ESgz0CsqdYtF32mcACE8wgcPtpJhGltSBusLm1mv6ub+xKILc2AZvP81Tys7RD+oTZiy10knIgDrAYRDsDn4EyyV7Gh60mxoo6huweF7LXwiVWntXnW0t5Rswi7SJBVhPAAyozD2YS5I+bTGI2UxxTbSI3vc=,iv:ChippGI7WwbO/qdd6R/IZHqQcQs+kU8EZluciU+sEs8=,tag:gfdHulP3DSuypBLhte1NRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
