apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  releaseName: headscale
  chart:
    spec:
      chart: headscale
      sourceRef:
        kind: HelmRepository
        name: headscale
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v0.27.1
    env:
      HEADSCALE_DNS_BASE_DOMAIN: "tsnet.men.sh"

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: ts.men.sh
            paths:
              - path: /

    serviceMonitor:
      main:
        enabled: true
