apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  releaseName: headscale
  chart:
    spec:
      chart: headscale
      sourceRef:
        kind: HelmRepository
        name: headscale
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v0.27.1
    env:
      HEADSCALE_DNS_BASE_DOMAIN: "tsnet.men.sh"

    sidecars:
      ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        env:
          - name: PORT
            value: "8090"
        ports:
          - name: http-ui
            containerPort: 8090
    service:
      main:
        ports:
          ui:
            port: 8090

    ingress:
      ui:
        enabled: true
        hosts:
          - host: ts.men.sh
            paths:
              - path: /web
                service:
                  port: 8090
        tls:
          - secretName: headscale-tls
            hosts:
              - ts.men.sh
      main:
        enabled: true
        className: traefik
        tls:
          - secretName: headscale-tls
            hosts:
              - ts.men.sh
        hosts:
          - host: ts.men.sh
            paths:
              - path: /
                pathType: Prefix

    serviceMonitor:
      main:
        enabled: true
