apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headscale
  namespace: headscale
spec:
  releaseName: headscale
  chart:
    spec:
      chart: headscale
      sourceRef:
        kind: HelmRepository
        name: headscale
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      config:
        enabled: true
        mountPath: /etc/headscale
        retain: true
        storageClass: "openebs-hostpath"
    image:
      tag: v0.27.1
    env:
      HEADSCALE_DNS_BASE_DOMAIN: "tsnet.men.sh"
      HEADSCALE_OIDC_ISSUER: "https://welcher.men.sh"
      HEADSCALE_OIDC_CLIENT_ID: "headscale"
      HEADSCALE_OIDC_CLIENT_SECRET: "351782476869337290"
      HEADSCALE_OIDC_PKCE_ENABLED: true

    sidecars:
      ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        env:
          - name: HTTP_PORT
            value: "8090"
        ports:
          - name: http-ui
            containerPort: 8090
    service:
      main:
        ports:
          ui:
            port: 8090

    ingress:
      ui:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        hosts:
          - host: ts.men.sh
            paths:
              - path: /web
                service:
                  port: 8090
        tls:
          - secretName: headscale-tls
            hosts:
              - ts.men.sh
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        tls:
          - secretName: headscale-tls
            hosts:
              - ts.men.sh
        hosts:
          - host: ts.men.sh
            paths:
              - path: /
                pathType: Prefix

    serviceMonitor:
      main:
        enabled: true
