---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg
      interval: 12h
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: false
