apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    zfs-localpv:
      crds:
        zfsLocalPv:
          enabled: true
        csi:
          volumeSnapshots:
            enabled: true

    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: true
      replicated:
        mayastor:
          enabled: false

    loki:
      enabled: true

      loki:
        commonConfig:
          replication_factor: 1

      singleBinary:
        replicas: 1
        drivesPerNode: 1
        persistence:
          enabled: true

      minio:
        enabled: true
        replicas: 1
        mode: standalone
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs
allowVolumeExpansion: true
parameters:
  recordsize: "128k"
  compression: "zstd"
  dedup: "off"
  fstype: "zfs"
  poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
