apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
