apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs
spec:
  interval: 5m
  url: https://seaweedfs.github.io/seaweedfs-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-operator
  namespace: seaweedfs
spec:
  releaseName: seaweedfs-operator
  chart:
    spec:
      chart: seaweedfs-operator
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-operator
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    webhook:
      enabled: false
