apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-cluster
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 1Gi
  managed:
    roles:
      - name: nextcloud
        ensure: present
        comment: Nextcloud User
        login: true
        superuser: false

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  name: nextcloud
  owner: nextcloud
  cluster:
    name: nextcloud-cluster
