apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-pg
  namespace: nextcloud
spec:
  instances: 1
  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: nextcloud-db
      owner: app
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
