apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-cluster
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: app
        createdb: true
        login: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  name: nextcloud
  owner: app
  cluster:
    name: nextcloud-cluster
