apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/affinity: cookie
    nextcloud:
      host: nextcloud.staging
      configs:
      other.config.php: |-
        <?php
        $CONFIG = array (
          'maintenance_window_start' => 100,
          0 => array (
            0 => 'phonetrack',
            1 => 'apporder',
            2 => 'quota_warning',
            3 => 'files_markdown',
            4 => 'socialsharing_email',
            5 => 'extract',
            6 => 'impersonate',
            7 => 'deck',
            8 => 'metadata',
            9 => 'files_downloadactivity',
            10 => 'files_retention',
          ),
          'jpeg_quality' => 60,
          'loglevel' => 2,
          'app_install_overwrite' => array (
            0 => 'extract',
            1 => 'solid',
            2 => 'forms',
            3 => 'secrets',
            4 => 'caniupdate',
          ),
          'enable_previews' => true,
          'enabledPreviewProviders' => array (
            0 => 'OC\\Preview\\TXT',
            1 => 'OC\\Preview\\PDF',
            2 => 'OC\\Preview\\Image',
            3 => 'OC\\Preview\\Photoshop',
            4 => 'OC\\Preview\\TIFF',
            5 => 'OC\\Preview\\SVG',
            6 => 'OC\\Preview\\Movie',
            7 => 'OC\\Preview\\MKV',
            8 => 'OC\\Preview\\MP4',
            9 => 'OC\\Preview\\AVI',
            10 => 'OC\\Preview\\HEIC',
          ),
          'memories.db.triggers.fcu' => true,
          'memories.exiftool' => '/var/www/nextcloud/apps/memories/bin-ext/exiftool-amd64-glibc',
          'memories.vod.path' => '/var/www/nextcloud/apps/memories/bin-ext/go-vod-amd64',
          'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
          'memories.vod.ffprobe' => '/usr/bin/ffprobe',
          'memories.vod.disable' => false,
          'memories.exiftool_no_local' => true,
          'memories.gis_type' => 1,
        );
    redis:
      enabled: true
    cronjob:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-cluster-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    metrics:
      enabled: true
