apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stalwart # Make general- purpose
  namespace: stalwart
spec:
  interval: 5m
  type: oci
  url: oci://codeberg.org/wrenix/helm-charts/
