apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu
  namespace: mailu
spec:
  releaseName: mailu
  chart:
    spec:
      chart: mailu
      sourceRef:
        kind: HelmRepository
        name: mailu
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    domain: men.sh
    hostnames:
      - men.sh
    existingSecret: mailu-key
    timezone: Europe/Berlin
    global:
      storageClass: openebs-zfs
    clamav:
      persistence:
        storageClass: openebs-zfs
    redis:
      master:
        persistence:
          storageClass: openebs-zfs
    front:
      hostPort:
        enabled: false
      externalService:
        enabled: true
        type: LoadBalancer
        annotations:
          kube-vip.io/loadbalancerIPs: 217.64.151.159
    initialAccount:
      enable: true
      username: admin
      domain: men.sh
      existingSecret: initial-account
      existingSecretPasswordKey: password
    externalDatabase:
      enabled: true
      type: postgresql
      host: mailu-pg-rw.mailu.svc.cluster.local
      port: "5432"
      existingSecret: mailu-pg-app
      existingSecretPasswordKey: password
    persistence:
      storageClass: ceph-filesystem
    ingress:
      enabled: true
      tls:
        - secretName: mailu-tls
          hosts:
            - mail.men.sh
      hosts:
        - host: mail.men.sh
          paths:
            - path: /
              pathType: Prefix
