apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: media.staging
          paths:
            - path: /
              pathType: Prefix
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
