---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h0m0s
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
  interval: 1h0m0s
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      namespace: velero
      features: EnableCSI
      backupStorageLocation:
        - name: encrypt
          provider: aws
          bucket: velero-backup
          default: true
          credential:
            name: velero-encrypt-auth
            key: file
          config:
            region: weur
            s3Url: http://velero-encrypt.velero.svc.cluster.local
      volumeSnapshotLocation:
        - name: encrypt
          provider: aws
          bucket: velero-backup
          default: true
          credential:
            name: velero-encrypt-auth
            key: file
          config:
            region: weur
            s3Url: http://velero-encrypt.velero.svc.cluster.local
