---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h0m0s
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
  interval: 1h0m0s
  values:
    deployNodeAgent: true
    kubectl:
      image:
        repository: public.ecr.aws/bitnami/kubectl
        tag: latest
    initContainers:
      - name: openebs-plugin
        image: openebs/velero-plugin:3.6.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      namespace: velero
      features: EnableCSI
      backupStorageLocation:
        - name: r2
          provider: aws
          bucket: velero-backup
          default: true
          credential:
            name: velero-auth
            key: cloud
          config:
            region: weur
            s3Url: https://b12e2beeb323c2c78eb536e955adbee1.r2.cloudflarestorage.com
            s3ForcePathStyle: "true"
      volumeSnapshotLocation:
        - name: r2
          provider: openebs.io/zfspv-blockstore
          config:
            bucket: velero-backup
            prefix: zfs
            namespace: openebs # this is the namespace where ZFS-LocalPV creates all the CRs, passed as OPENEBS_NAMESPACE env in the ZFS-LocalPV deployment
            provider: aws

            credential:
              name: velero-auth
              key: cloud
            region: weur
            s3ForcePathStyle: "true"
            s3Url: https://b12e2beeb323c2c78eb536e955adbee1.r2.cloudflarestorage.com
