apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: kube-system
stringData:
    privateKey: ENC[AES256_GCM,data:QaQoiJ7uv6WNni7hsHRFm7Jse+cjp+JVIZPDRJfF7jHAuLWHX19mHpM6IFE=,iv:nA/4v7O96IuMj14YZKbo2VoPBRPiATFXW9XAIx3rr5Y=,tag:AK2sqvRyP2gDz7ckAJVV3w==,type:str]
    peerPublicKey: ENC[AES256_GCM,data:LXF9QvmMQcyT9njcEWBWrg6mUOsSdBLNZHoDwRvao1V0Sn78zYH7C2iY9bE=,iv:v9UGM+LQvnbHaHt7CMLwvmJ8oLAYLL7VnUdLa/zWWLo=,tag:Akvr/zHtOunsEvpIyOxbfw==,type:str]
    peerEndpoint: ENC[AES256_GCM,data:tHRfmXs7rF5b5hXNPBbTPuEkR058YNPb/mnU8aX1,iv:p9ngPq6TvDwTaeXH+bTC0sYibdxlRHEtXbXp0x5Nwkc=,tag:MMOlYGmS1uxw/nzjzItxLQ==,type:str]
    allowedIPs: ENC[AES256_GCM,data:xxpuJVKrRkGknCdMLnEb5A==,iv:8vi3k1pT+90bmmkmx6lPbu/NfSpg4ZmZ0Mj+L5TDf3I=,tag:ALyXmmBmN9gDsbrGz1/EnA==,type:str]
    routes: ENC[AES256_GCM,data:ZOZCChekVO4GOohkyunVYg==,iv:fb07NB2/KM/fz2V94XKzT+Ry5M+uMcdU0IIGU0YxiXc=,tag:hryuTWnE8Zz8VB88cc3N4Q==,type:str]
sops:
    age:
        - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YWxucWlVSng4N0tzUHdj
            UWFXTWh3UmJ5VUJkYlJNbjFxN0JUbXkwZ2pRCjMxbWo1YUdJVXZhSDZEY3BIaFVa
            eWZVdGNKYnlsdU96V29PcXMxNjdFZ1kKLS0tIGhhY0FmZ05lT2YwZys4UHIzZ1A5
            bnVkOHZiQ2Y5aUxLUGdXZnFEaC9JSGsKz1P0A30RmuhhxDBQ+0w15LhxgUXpemi8
            MrSYQnuWSMJss3kR6wyYhebqCgFhUmQJ1zXpOiEpr9Z6E005Z7ON+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzhxreet79v0hk8wzsqxtrn3fvala7zk5edxa85ydaxum8jfa9tsa0kjck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFJLeXkyaHU0aGpOUmoz
            cUxrNnlFVXg5SWw2eFNMYXhtdnRWRmMzN0JBCjVvNnJkcUFUcFBwbW5BVHR2TWl3
            bEQwSkpOQlRHbUFvcVJIU1ZsZXJYODAKLS0tIG9MNEFxMG0yNVNEUkcxRWZ4Y2hO
            bWhWOTNSd0VXUjlINXNqdmdpU1NPMGsK6rSr/pET00GLujTwONMPQKkXhX8YJric
            VDcsjyEbujH76xQPTkwzcnexhdSvRiK9hBw5XWAiI6n76vzyNuKaNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQitKRmZ1RGUyZlZRRURo
            MmhPazEyVEZPS3pMN1hwS3lNSUljeFZWSVRzCjZJYXRhMXF4dU9ZWlZES05QTHlm
            NHBCU1JOeEY2TVRkRDZRZVVGZXZHV1UKLS0tIFRhMTlzVmVxOE5RbEtuTFB3RDhL
            aTIrWStObkVXWEtzTU1RK09uUU5NWDAK547JSoHLousWcGEyQYiggMQZWT+aPhAw
            5IiQzF2oHB45YrZWRfQdwNcSuWZkM63u3S7lAB1IG781emc+crzrBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T21:08:15Z"
    mac: ENC[AES256_GCM,data:AUNiat8uwo4TAf6Re+X+pBI8MqGlHAmqE4ys4E2eQv/zAY9Jpd1OBXgvEuEvyLF5THxjsv6gw4uKcS1ePp4AqIToacxPi1ks1O9bfO2jlKSNbna46KbP7PESUIVVfM3/UeNiPaiF772ddy3i/5ldd2Rb+MdmTNMPwF5t9hXSiLw=,iv:1iRtym0BokNxadUow2PeU1Na4XReW5DJA5yA59FIJfw=,tag:3PKVlroYH102U2YOnAj/PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
