apiVersion: v1
kind: Secret
metadata:
    name: wireguard1
    namespace: kube-system
stringData:
    privateKey: ENC[AES256_GCM,data:0bQmhgbpfYpq0O7W4/6RZ9HGh1WZkEpC54i1OByqwLfyqBv644eOynELnmU=,iv:zZ9TfjW8rLtRwWsFllpQNPzMqHoUFeWhlokUlGNk5Tc=,tag:FRhKV1rgOuV2pIkhr0PuvA==,type:str]
    peerPublicKey: ENC[AES256_GCM,data:PWoVj9Z1l6CUjCOd7e7OisFZv+aaswAsWKA5uBYfpOmMOeIFLYmKOdGF81o=,iv:5m0r5NNpInJ12fnnzCgz23I9IOXUR2NV/wN89+Nydi4=,tag:TgIHMjwUwRa/jsRA50a5EA==,type:str]
    peerEndpoint: ENC[AES256_GCM,data:Hwq2OeZqpFAu7a/GKYpiJm4=,iv:jx2g71SWvjDaQJAw9+IMdsfaQjbTC6dLsY3zM9ZN4mM=,tag:HLfl4VsUKGIUEipVqDYYaw==,type:str]
    allowedIPs: ""
sops:
    age:
        - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YWxucWlVSng4N0tzUHdj
            UWFXTWh3UmJ5VUJkYlJNbjFxN0JUbXkwZ2pRCjMxbWo1YUdJVXZhSDZEY3BIaFVa
            eWZVdGNKYnlsdU96V29PcXMxNjdFZ1kKLS0tIGhhY0FmZ05lT2YwZys4UHIzZ1A5
            bnVkOHZiQ2Y5aUxLUGdXZnFEaC9JSGsKz1P0A30RmuhhxDBQ+0w15LhxgUXpemi8
            MrSYQnuWSMJss3kR6wyYhebqCgFhUmQJ1zXpOiEpr9Z6E005Z7ON+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzhxreet79v0hk8wzsqxtrn3fvala7zk5edxa85ydaxum8jfa9tsa0kjck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFJLeXkyaHU0aGpOUmoz
            cUxrNnlFVXg5SWw2eFNMYXhtdnRWRmMzN0JBCjVvNnJkcUFUcFBwbW5BVHR2TWl3
            bEQwSkpOQlRHbUFvcVJIU1ZsZXJYODAKLS0tIG9MNEFxMG0yNVNEUkcxRWZ4Y2hO
            bWhWOTNSd0VXUjlINXNqdmdpU1NPMGsK6rSr/pET00GLujTwONMPQKkXhX8YJric
            VDcsjyEbujH76xQPTkwzcnexhdSvRiK9hBw5XWAiI6n76vzyNuKaNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQitKRmZ1RGUyZlZRRURo
            MmhPazEyVEZPS3pMN1hwS3lNSUljeFZWSVRzCjZJYXRhMXF4dU9ZWlZES05QTHlm
            NHBCU1JOeEY2TVRkRDZRZVVGZXZHV1UKLS0tIFRhMTlzVmVxOE5RbEtuTFB3RDhL
            aTIrWStObkVXWEtzTU1RK09uUU5NWDAK547JSoHLousWcGEyQYiggMQZWT+aPhAw
            5IiQzF2oHB45YrZWRfQdwNcSuWZkM63u3S7lAB1IG781emc+crzrBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T16:38:23Z"
    mac: ENC[AES256_GCM,data:uXzWusHj0lxGmyheiMrh147FgBbpcKRh/tjghSMi/d7saKRGI8XWtqYJl+Ud1tIGBlkSJD/xYSzvu5D8wT7ZvXuuoJbIeyrPe/vHAJ/GwT8V2FHEODaKvcn0pymDzg7wkQGi5szqlsYyj2gl/oaRrN36CUh+2rVK6j40X2q4aVo=,iv:yXPNAAPU0qzeTvN8wnDUZAxTgFpvtByK3y8pCccieso=,tag:DBeP2HyzX5kyxc0BfoHVkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: kube-system
stringData:
    tunnels: ENC[AES256_GCM,data:mG0lTpSIJxX+ZwDH/JKaT9P4JFzXoD6pwANrwxJkVFZC+4VIBGqO1lB+DU1VyTQPjjnaqt76/b89SRRTxqCwDb49Cs9xTSkIWY/VezaIwMmHg9SSYqaheRDYsdC2r2KooA+8BuZPNVHLSvUtLdw6jS57Vx+slNeSWMhbrE27C4/eIvNNDbxbKhynP5V628vsIVCRDEjiC1BiRdwtI79oegKQOxWYjV8Y9ZwL1FG0LsyDD6iUpPMgiYpM2qsRW/YapZV0jeavgdFh3cmhj8IgXRyn2orYYa9a5gIwPuyQ3NIJf0gYFn3d8tfQbCNqyccf8bk5+gUU3bIwjP+la/xFBGDvP9R7TQ8S/+QaeotKKFJCDGM=,iv:YTpiB+Dg6YbhnnwETdSCXZNIZ7eOiKMOnwKKNp32SrA=,tag:sMF9X45Q12Jh96E30UD7nQ==,type:str]
    allowedIPs: ENC[AES256_GCM,data:BD59h1o6S0KwWjQap8vdjEhEOM3GEwGWVmi5KCHWT8yE2Yha9wJ0QXCeb3vWrWM8f60hjh+TKgBBQmYsAu8egf29o4rx1RiZAmu7k9/tZfUMmnnGN4Lk8ooPS9UYqWuHu1rMyekcdbXacD3seLyp34QNjUPWEHRzeIpdIuqSgH5ibq3Sh+abWoHOUpDF9+dK4EC07QEgkFEDklN9ZrmMmy/IvK7qa3339KK6fTfrpC/44voo0so415J3FBw2HqL4swqbO3k3g1zcrt0T0oj7z8zJ34Xed6J6ea9HurwosD/LJdzDAZS14GcImacPxlZIbEjsatjsD8LeCpsG+qJS828kmVFeWR2/qK2V04+bRk8u/5GUEL20aj5FilSVJdIGSbqwkItdk8EiTiSL8l5kMZjDq+0uzu/v9J4IdJL8ZYnC1/qR9uqotHlKVm/kYGG/SKwhUq1PsG1j/iKpXbgOGhSUdI21IDvw,iv:BLYqCK2qvd8j7mHkZ/hcPoNEcoXVD5uhEhb+dLrrGWU=,tag:lAbvudKA6e8FldtkWcx+xw==,type:str]
sops:
    age:
        - recipient: age1yvcq2p43h023m8ds5qjyc96p48kd4p4f8f7hux8dsjcv7tfehvaqjut87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YWxucWlVSng4N0tzUHdj
            UWFXTWh3UmJ5VUJkYlJNbjFxN0JUbXkwZ2pRCjMxbWo1YUdJVXZhSDZEY3BIaFVa
            eWZVdGNKYnlsdU96V29PcXMxNjdFZ1kKLS0tIGhhY0FmZ05lT2YwZys4UHIzZ1A5
            bnVkOHZiQ2Y5aUxLUGdXZnFEaC9JSGsKz1P0A30RmuhhxDBQ+0w15LhxgUXpemi8
            MrSYQnuWSMJss3kR6wyYhebqCgFhUmQJ1zXpOiEpr9Z6E005Z7ON+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzhxreet79v0hk8wzsqxtrn3fvala7zk5edxa85ydaxum8jfa9tsa0kjck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFJLeXkyaHU0aGpOUmoz
            cUxrNnlFVXg5SWw2eFNMYXhtdnRWRmMzN0JBCjVvNnJkcUFUcFBwbW5BVHR2TWl3
            bEQwSkpOQlRHbUFvcVJIU1ZsZXJYODAKLS0tIG9MNEFxMG0yNVNEUkcxRWZ4Y2hO
            bWhWOTNSd0VXUjlINXNqdmdpU1NPMGsK6rSr/pET00GLujTwONMPQKkXhX8YJric
            VDcsjyEbujH76xQPTkwzcnexhdSvRiK9hBw5XWAiI6n76vzyNuKaNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vnmsvg4s2uxzz4rm3apnt4dpczc5njans0el4d3glx92atynf8sla5l7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQitKRmZ1RGUyZlZRRURo
            MmhPazEyVEZPS3pMN1hwS3lNSUljeFZWSVRzCjZJYXRhMXF4dU9ZWlZES05QTHlm
            NHBCU1JOeEY2TVRkRDZRZVVGZXZHV1UKLS0tIFRhMTlzVmVxOE5RbEtuTFB3RDhL
            aTIrWStObkVXWEtzTU1RK09uUU5NWDAK547JSoHLousWcGEyQYiggMQZWT+aPhAw
            5IiQzF2oHB45YrZWRfQdwNcSuWZkM63u3S7lAB1IG781emc+crzrBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T16:38:23Z"
    mac: ENC[AES256_GCM,data:uXzWusHj0lxGmyheiMrh147FgBbpcKRh/tjghSMi/d7saKRGI8XWtqYJl+Ud1tIGBlkSJD/xYSzvu5D8wT7ZvXuuoJbIeyrPe/vHAJ/GwT8V2FHEODaKvcn0pymDzg7wkQGi5szqlsYyj2gl/oaRrN36CUh+2rVK6j40X2q4aVo=,iv:yXPNAAPU0qzeTvN8wnDUZAxTgFpvtByK3y8pCccieso=,tag:DBeP2HyzX5kyxc0BfoHVkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
